# Generated by Django 4.0.4 on 2023-01-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_comment_name_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='added_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
