# Generated by Django 4.0.4 on 2023-01-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_content_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(),
        ),
    ]
