# Generated by Django 4.0.4 on 2023-01-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='place',
        ),
    ]
