# Generated by Django 4.0.4 on 2023-01-20 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0008_rename_post_like_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='likes',
        ),
        migrations.AddField(
            model_name='place',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
